In [1]:
import torch

In [8]:
class A:
    def __init__(self, d):
        self.d = d

In [9]:
d = dict(a=1)
a = A(d)

In [11]:
a.d['a'] = 3

In [15]:
args.add_argument(n_user)

AttributeError: 'Namespace' object has no attribute 'add_argument'

In [2]:
import argparse

parser = argparse.ArgumentParser(description='NeuMF')

parser.add_argument('--ratings_path', required=False, default='data/ml-1m/ratings.dat')
parser.add_argument('--emb_dim', required=False, default=64)
parser.add_argument('--neg_ratio', required=False, default=3)
parser.add_argument('--prep_data_dir', required=False, default='prep_data')
parser.add_argument('--prep_data_name', required=False, default='prep_data.pkl')

args = parser.parse_args([])

In [3]:
# from arguments import args
from dataset.prepdataset import ML1mDataset
from dataset.customdataset import CustomDataset

from model import NeuMF
from trainer import Trainer



In [4]:
ml1m_dataset = ML1mDataset(args)


In [7]:
os.path.isfile(ml1m_dataset.get_prep_data_path())

True

In [5]:
ratings = ml1m_dataset.load_ratings_path()
ratings

user  item  rating  timestamp
0           1  1193       5  978300760
1           1   661       3  978302109
2           1   914       3  978301968
3           1  3408       4  978300275
4           1  2355       5  978824291
...       ...   ...     ...        ...
1000204  6040  1091       1  956716541
1000205  6040  1094       5  956704887
1000206  6040   562       5  956704746
1000207  6040  1096       4  956715648
1000208  6040  1097       4  956715569

[1000209 rows x 4 columns]

In [6]:
uidx_map = {user:i for i, user in enumerate(set(ratings['user']))}
iidx_map = {item:i for i, item in enumerate(set(ratings['item']))}


In [7]:
uidx_map = {user:i for i, user in enumerate(set(ratings['user']))}


In [ ]:
set(ratings['item'])

In [ ]:
iidx_map = {item:i for i, item in enumerate(set(ratings['item'])``)}


In [5]:
# if __name__ == '__main__':
ml1m_dataset.preprocess()
print('Done.')

Preprocess==================================================


In [16]:
ratings_path = 'data/ml-1m/ratings.dat'

In [59]:
import pandas as pd
ratings = pd.read_csv(ratings_path, names=['user', 'item', 'rating', 'timestamp'], sep='::', engine='python')
ratings

user  item  rating  timestamp
0           1  1193       5  978300760
1           1   661       3  978302109
2           1   914       3  978301968
3           1  3408       4  978300275
4           1  2355       5  978824291
...       ...   ...     ...        ...
1000204  6040  1091       1  956716541
1000205  6040  1094       5  956704887
1000206  6040   562       5  956704746
1000207  6040  1096       4  956715648
1000208  6040  1097       4  956715569

[1000209 rows x 4 columns]

In [99]:
uidx_map = {user:i for i, user in enumerate(set(ratings['user']))}
iidx_map = {item:i for i, item in enumerate(set(ratings['item']))}
ratings['uidx'] = ratings['user'].map(uidx_map)
ratings['iidx'] = ratings['item'].map(iidx_map)

In [100]:
n_user = ratings['uidx'].nunique()
n_item = ratings['iidx'].nunique()

In [101]:
import torch.nn as nn

In [ ]:
emb_dim = 64


In [17]:
class Card:
  suitList = ["CLubs"]
  number = 1

  def __init__ (self, rank = 0):
      self.rank = rank

  def __str__ (self):
      return (self.suitList[self.rank] + "  " + str(self.number) + ";\n")
c1 = Card()
c2 = Card()
print(c1)
c1.suitList[0] = "Heart"
c1.number = 3
print(c1)
print(c2)
c3 = Card()
print(c3)

CLubs  1;

Heart  3;

Heart  1;

Heart  1;



In [68]:
model = NeuMF(n_user, n_item, emb_dim)

In [75]:
logits = model(torch.tensor([3]), torch.tensor([4]))

In [87]:
logits

tensor([[0.8450]], grad_fn=<SigmoidBackward0>)

In [81]:
logits.size()

torch.Size([1, 1])

In [85]:
torch.tensor([1]).view(-1, 1).size()

torch.Size([1, 1])

In [92]:
from torch.utils.data import Dataset

In [94]:
ratings

user  item  rating  timestamp
0           1  1193       5  978300760
1           1   661       3  978302109
2           1   914       3  978301968
3           1  3408       4  978300275
4           1  2355       5  978824291
...       ...   ...     ...        ...
1000204  6040  1091       1  956716541
1000205  6040  1094       5  956704887
1000206  6040   562       5  956704746
1000207  6040  1096       4  956715648
1000208  6040  1097       4  956715569

[1000209 rows x 4 columns]

In [190]:
class CustomDataset(Dataset):
    def __init__(self, user, item, label):
        self.user = user
        self.item = item
        self.label = label

    def __getitem__(self, i):
        return self.user[i], self.item[i], self.label[i]
        
    def __len__(self):
        return len(self.user)


In [191]:
pos_items = ratings.groupby('uidx')['iidx'].agg(lambda x: set(x)).to_dict()

In [192]:
u = 1
u_pos_items = pos_items[u]

In [193]:
import numpy as np
neg_ratio = 3

neg_user, neg_item = [], []
for u in range(n_user):
    neg_items = list(set(range(n_item)) - u_positive_items)
    neg_samples = np.random.choice(neg_items, min(len(u_pos_items) * neg_ratio, len(neg_items)), replace=False)
    neg_user.extend([u] * len(neg_samples))
    neg_item.extend(neg_samples)



In [194]:
dataset = CustomDataset(ratings['uidx'].tolist() + neg_user,
            ratings['iidx'].tolist() + neg_item,
            [1] * len(ratings) + [0] * len(neg_user)
)

In [195]:
from torch.utils.data import DataLoader

In [196]:
from torch.utils.data import Dataset, DataLoader, random_split

In [197]:
n_train_sample = len(dataset)
n_train_sample


3337689

In [198]:
n_sample = len(dataset)
n_train = int(n_sample*0.9)
n_valid = n_sample - n_train
train_dataset, test_dataset = random_split(dataset, [n_train, n_valid])  # del dataset? memory problem

In [199]:
train_dataloader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_dataloader = DataLoader(test_dataset, batch_size=64, shuffle=False)

In [202]:
label

tensor([1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0])

In [218]:
import torch.optim as optim


In [220]:

label

tensor([0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
        1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [222]:

from tqdm.auto import tqdm

In [224]:
criterion = nn.BCELoss()
learning_rate = 0.01
n_epoch = 30
optimizer = optim.SGD(model.parameters(), lr=learning_rate)
model.train()
for epoch in range(1, n_epoch+1):
    print(f"epoch : {epoch}")
    for user, item, label in tqdm(train_dataloader):
        optimizer.zero_grad() 
        logits = model(user, item)
        label = label.type(torch.FloatTensor)
        loss = criterion(logits.flatten(), label)
        loss.backward()
        optimizer.step()



epoch : 1


100%|██████████| 46937/46937 [01:41<00:00, 464.17it/s]


epoch : 2


100%|██████████| 46937/46937 [01:37<00:00, 479.19it/s]


epoch : 3


100%|██████████| 46937/46937 [01:37<00:00, 480.36it/s]


epoch : 4


100%|██████████| 46937/46937 [01:37<00:00, 479.92it/s]


epoch : 5


100%|██████████| 46937/46937 [01:41<00:00, 462.55it/s]


epoch : 6


100%|██████████| 46937/46937 [01:39<00:00, 471.78it/s]


epoch : 7


100%|██████████| 46937/46937 [01:41<00:00, 462.54it/s]


epoch : 8


100%|██████████| 46937/46937 [01:34<00:00, 496.43it/s]


epoch : 9


100%|██████████| 46937/46937 [01:30<00:00, 520.58it/s]


epoch : 10


100%|██████████| 46937/46937 [01:29<00:00, 522.22it/s]


epoch : 11


100%|██████████| 46937/46937 [01:29<00:00, 527.24it/s]


epoch : 12


100%|██████████| 46937/46937 [01:28<00:00, 532.83it/s]


epoch : 13


100%|██████████| 46937/46937 [01:28<00:00, 529.82it/s]


epoch : 14


100%|██████████| 46937/46937 [01:28<00:00, 529.42it/s]


epoch : 15


100%|██████████| 46937/46937 [01:27<00:00, 535.64it/s]


epoch : 16


100%|██████████| 46937/46937 [01:28<00:00, 528.33it/s]


epoch : 17


100%|██████████| 46937/46937 [01:29<00:00, 526.99it/s]


epoch : 18


100%|██████████| 46937/46937 [01:27<00:00, 538.29it/s]


epoch : 19


100%|██████████| 46937/46937 [01:28<00:00, 529.28it/s]


epoch : 20


100%|██████████| 46937/46937 [01:29<00:00, 523.19it/s]


epoch : 21


100%|██████████| 46937/46937 [01:27<00:00, 535.64it/s]


epoch : 22


100%|██████████| 46937/46937 [01:30<00:00, 519.36it/s]


epoch : 23


100%|██████████| 46937/46937 [01:29<00:00, 522.70it/s]


epoch : 24


100%|██████████| 46937/46937 [01:33<00:00, 504.01it/s]


epoch : 25


100%|██████████| 46937/46937 [01:44<00:00, 447.21it/s]


epoch : 26


100%|██████████| 46937/46937 [01:44<00:00, 447.87it/s]


epoch : 27


100%|██████████| 46937/46937 [01:42<00:00, 459.38it/s]


epoch : 28


100%|██████████| 46937/46937 [01:47<00:00, 438.21it/s]


epoch : 29


100%|██████████| 46937/46937 [01:45<00:00, 443.95it/s]


epoch : 30


100%|██████████| 46937/46937 [01:41<00:00, 461.36it/s]


In [227]:
torch.save(model.state_dict(), 'result/neumf.pth')

In [242]:
model.eval()
correct, total = 0, 0
with torch.no_grad():
    for user, item, label in tqdm(test_dataloader):
        logits = model(user, item)
        label = label.type(torch.FloatTensor)

        correct += torch.sum((logits.flatten()>=0.5) == label).item()
        total += len(label)
print(f"acc : {correct/total:.4f}")

100%|██████████| 5216/5216 [00:01<00:00, 2831.93it/s]

acc : 0.8121


In [245]:
(logits.flatten()>=0.5)

tensor([False, False,  True, False, False,  True,  True, False, False])

In [244]:
label

tensor([0., 0., 1., 0., 1., 1., 1., 0., 0.])

In [249]:
torch.sum((logits.flatten()>=0.5) == label).item() / len

TypeError: unsupported operand type(s) for /: 'int' and 'builtin_function_or_method'

tensor(0.7841, grad_fn=<BinaryCrossEntropyBackward0>)